spring.application.name=backend

spring.security.user.name=user
spring.security.user.password=123

# JWT settings
jwt.secret=U2FtcGxlU2VjcmV0S2V5U2FtcGxlU2VjcmV0S2V5U2FtcGxlU2VjcmV0S2V5
jwt.expiration=86400000