spring.application.name=backend

spring.security.user.name=user
spring.security.user.password=123

# JWT settings
jwt.secret=U2FtcGxlU2VjcmV0S2V5U2FtcGxlU2VjcmV0S2V5U2FtcGxlU2VjcmV0S2V5
jwt.expiration=15

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.username=saljaoui
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false