spring.application.name=backend

# ========= SERVER =========
server.port=8080
server.connection-timeout=10s
server.error.include-message=always
server.error.include-binding-errors=always

# ========= SECURITY =========
spring.security.filter.dispatcher-types=request,error

# ========= JWT =========
jwt.secret=U2FtcGxlU2VjcmV0S2V5U2FtcGxlU2VjcmV0S2V5U2FtcGxlU2VjcmV0S2V5
jwt.expiration=30

# ========= FILE UPLOAD =========
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ========= DATABASE =========
spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.username=saljaoui
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ========= LOGGING =========
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ========= JSON =========
spring.jackson.deserialization.fail-on-unknown-properties=false